bin/version.js, cli.js, package.json, source/_version.css
Load `package.json` of "lifecycle script" reliably.
Use homepage form `package.json`.
- https://github.com/TACC/Core-CMS/pull/448
- Fix variable name from `path` to `package`.
- Do not depend on assumed relative directory for `package.json`.
- Make calls to `package.json` using reliable path from NPM.
- Add and use `package.json` homepage.
✓ I tested `npm run build` on user repo https://github.com/TACC/Core-CMS/tree/test/core-styles--solution-b.
I discovered these changes when I found `process.env.npm_package_homepage` was `undefined` then came across:
https://github.com/npm/rfcs/blob/main/implemented/0021-reduce-lifecycle-script-environment.md#detailed-explanation
=> Quick: Stable Package.json Calls & Add Homepage

source/_imports/objects/o-section.css
Remove legacy selectors.
- requires https://github.com/TACC/Core-CMS/pull/151
- mirrors https://github.com/TACC/Core-CMS-Resources/pull/133
- Delete legacy part of CSS selectors.
=> chore(gh-149): remove deleted id selector

source/_imports/settings/props.space.css
Use pixels for standard space props.
This will ensure that if base font changes, spacing is not affected.
This is Designer decision from [Shared UI - Constants - Units](https://confluence.tacc.utexas.edu/x/dYAZCg).
=> feat(gh-99): use pixel for standard space props

source/_imports/components/c-nav.css, source/_imports/components/c-nav.html
Add nav component.
- [ECEP-114](https://jira.tacc.utexas.edu/browse/ECEP-114)
- required by https://github.com/TACC/Core-CMS/pull/464
- required by [another ECEP-114 PR yet to be made]
1. Review [Core Nav Pattern (dev)].
1. Change screen size from wide to narrow and back.
1. On wide screen:
- links should have **less** space between them.
- link vertical clickable area should extend **a tad** beyond its text
- link horizontal clickable area should extend _a tad_ beyond its text
1. On narrow screen:
- links should have **more** space between them
- link vertical clickable area should extend **well** beyond its text
- link horizontal clickable area should extend _a tad_ beyond its text
1. Previous features must not have changed:
- boxed unordered list item have bullets prefixes
- ordered …
=> feat: nav component

source/_imports/components/django.cms.css, source/_imports/objects/o-section.css, source/_themes/default.json, source/_themes/has-dark-logo.json
Support `position: sticky` elements (using Bootstrap class) for Django CMS.
- [ECEP-114](https://jira.tacc.utexas.edu/browse/ECEP-114)
- required by https://github.com/TACC/Core-CMS/pull/464
https://github.com/TACC/Core-CMS/pull/464
=> feat: position sticky support on CMS

source/_imports/objects/o-flex-item-table-wrap.css
Copy object module `o-flex-item-table-wrap` from [TACC/Core-Portal](https://github.com/TACC/Core-Portal/blob/d136b2a/client/src/styles/objects/o-flex-item-table-wrap.css).
- required by https://github.com/wesleyboar/Core-Components
Skipped. Portal uses it. Core-Components uses it. Just need the styles available import as is. It was already modular.
=> feat(object): o-flex-item-table-wrap (Core-Portal)

source/_imports/tools/x-truncate.css
Fix typo that was rendering `%x-truncate--one-line` unusable.
N/A
=> fix(x-truncate): typo kills x-truncate--one-line

source/_imports/elements/figure.css
Figure images that are nested in anchor tags should also have margin-bottom, not just unlinked figure images.
- [FP-1542](https://jira.tacc.utexas.edu/browse/FP-1542)
- required by https://github.com/TACC/Core-CMS/pull/493
- margin-bottom for linked figure images too
See https://github.com/TACC/Core-CMS/pull/493.
=> fix(fp-1542): figure img margin for link img's too

source/_imports/objects/o-offset-content.css
Reduce offset content default distance.
<details>Only used ECEP and TUP, which use default styles, and Texascale which overrides value. This accommodates news articles being centered (), which gave offset content less space.</details>
- [TUP-151](https://jira.tacc.utexas.edu/browse/TUP-151)
- required by and requires https://github.com/TACC/Core-CMS/pull/488
- reduce offset distance
See https://github.com/TACC/Core-CMS/pull/488.
=> feat(tup-151): offset content less offset

CHANGELOG.md, package.json
Bump version (to prepare for use by client software PRs).
After this, I'll change v1–v3 to v0.3–v0.5, because this repo is still not stable.
=> chore(version): v3

CHANGELOG.md, README.md, package-lock.json, package.json
Change versions (to reflect volatile state of API):
| | | | |
| - | - | - | - |
| from | v1.0.0 | v2.0.0 | v3.0.0 |
| to | v0.3.0 | v0.4.0 | v0.5.0 |
many open PRs that should point to a specific version (or commit)
- version change (package, package-lock, changelog)
- add publish instructions to readme
- (external) changed all git tags[^1] and GitHub releases
[^1]: The new git tags were also annotated with the commit message.
N/A
=> chore(version): v3.0→v0.5 & publish instructions

CHANGELOG.md, README.md, package-lock.json, package.json
Version update from v0.5.0 to v0.5.1.
- update changelog
- update version in `package.json`
- update version in `package-lock.json` (manually, because `npm i --package-lock-only` did not work)
- fix date of v0.5.0 release
- tweak publish instructions
=> chore(version): v0.5.0→v0.5.1 & instructions tweak

source/_imports/components/c-button.css
A tiny bit more vertical padding for buttons ([reason](https://tacc-team.slack.com/archives/CQUA4D5KJ/p1654877292004179?thread_ts=1654815547.469369&cid=CQUA4D5KJ)).
- https://github.com/TACC/Core-Portal/pull/649
- padding tweak
Skipped.
Negligible.
=> fix(fp-1678): small button a bit more vert pad

src/lib/_imports/components/bootstrap.container.css, src/lib/_imports/components/bootstrap.pagination.css, src/lib/_imports/components/c-button.css, src/lib/_imports/components/c-callout.css, src/lib/_imports/components/c-card.css, src/lib/_imports/components/c-data-list.css, src/lib/_imports/components/c-nav.css, src/lib/_imports/components/c-see-all-link.css, src/lib/_imports/components/c-show-more.css, src/lib/_imports/objects/o-grid.css, src/lib/_imports/objects/o-offset-content.css, src/lib/_imports/objects/o-section.css, src/lib/_imports/tools/x-layout.css, src/lib/_imports/trumps/s-article-list.css, src/lib/_imports/trumps/s-article-preview.css, src/lib/_imports/trumps/s-breadcrumbs.css, src/lib/_imports/trumps/s-system-specs.css
Use relative paths, like [tup-ui].
<sup>These changes got merged to [tup-ui] `main` via https://github.com/TACC/tup-ui/pull/38. The original isolated change is some earlier [tup-ui] PR.</sup>
[tup-ui]: https://github.com/TACC/tup-ui/
None
- Replace vague paths with relative paths.
1. `npm ci`
2. `npm run build`
3. no errors
<sup>I tested this even further atop #34 via `npm run start` and `npm run build:demo`.</sup>
N/A
=> feat: use relative paths like tup-ui

bin/build.js, bin/test.js, package.json
Replace core-styles build and test CLI commands with tiny scripts.
N/A
- update `package.json` to run script
- add scripts that use module, not CLI 
1. `cd libs/core-styles`
1. `npm ci`
1. `npm run build`, no errors
1. `npm run test`, no errors
- [How to Test Core Styles Build Chain, Quick Way](https://github.com/TACC/tup-ui/wiki/Test-Styles-Build-Chain,-Quick-Way)
- [Test Styles Build Chain, Long Way](https://github.com/TACC/tup-ui/wiki/Test-Styles-Build-Chain,-Long-Way)
N/A (no change expected)
CMS no longer uses the CLI. Core-Styles itself need not use it either.
If CLI continues to prove unnecessary, delete it (and commander dependency).
=> chore: retire internal usage of cli

src/lib/_imports/tools/x-mailto-text-replace.css, src/lib/_imports/trumps/u-mailto-text-replace.css, src/lib/_imports/trumps/u-mailto-text-replace/u-mailto-text-replace.config.yml, src/lib/_imports/trumps/u-mailto-text-replace/u-mailto-text-replace.hbs
Replace text of `mailto:` links using data attributes (if available).
<details>
The details are added automatically by JavaScript from https://github.com/TACC/Core-CMS/pull/546.
</details>
- [ECEP-214](https://jira.tacc.utexas.edu/browse/ECEP-214)
- required by https://github.com/TACC/Core-CMS/pull/546
- add new pattern `u-mailto-text-replace`
0. `npm ci`
1. `npm run build`
2. `npm run start`
3. Navigate to Core > Trumps > Mailto Link Text Replacement.
4. Verify top link has no attributes and shows its actual link text.
5. Verify bottom link has data attributes and shows link text that is an altered e-mail address.
See https://github.com/TACC/Core-CMS/pull/546.
| Core Styles | Core CMS |
| - | - |
| ![Core-Styles](https://user-images.githubusercontent.com/62723358/186036055-0802b91a-bef8-4 …
=> feat(trumps): u-mailto-text-replace (for ecep 214)

CHANGELOG.md, package-lock.json, package.json
Publish v0.9.0.
- [FP-1903](https://jira.tacc.utexas.edu/browse/FP-1903)
- publishes https://github.com/TACC/Core-Styles/pull/41
- changelog
- package(-lock).json
N/A (direct publish of https://github.com/TACC/Core-Styles/pull/41)
The **breaking change** `.../elements/html-elements.css` → `.../elements/html-elements.cms.css` is already accounted for:
- https://github.com/TACC/Core-CMS/pull/531
- https://github.com/TACC/Core-CMS-Resources/pull/158
=> chore: v0.9.0

src/lib/_imports/components/c-button.css
Buttons should be automatic width by default.
- [FP-1791](https://jira.tacc.utexas.edu/browse/FP-1791)
- required by https://github.com/TACC/Core-CMS/pull/560
- Do not default width to short.
- Do not set font size (let client do so, or not).
Pages:
- https://apcd-qa.tacc.utexas.edu/register/request-to-submit
- https://apcd-qa.tacc.utexas.edu/register/request-to-submit-form
Steps:
1. Submit buttons are as wide as their text content (plus padding).
2. Submit buttons width is **not** fixed by a snippet.
Tested via consumer app; see https://github.com/TACC/Core-CMS/pull/560.
=> fix(c-button): fp-1791 auto width by default

src/lib/_imports/components/bootstrap.form.css, src/lib/_imports/components/portal/bootstrap/bootstrap.form/README.md, src/lib/_imports/components/portal/bootstrap/bootstrap.form/bootstrap.form.config.yml, src/lib/_imports/components/portal/bootstrap/bootstrap.form/bootstrap.form.hbs, src/lib/_imports/components/portal/bootstrap/bootstrap.form/bootstrap.form_docs.css
Add bootstrap form (Portal only).
- [TUP-356](https://jira.tacc.utexas.edu/browse/TUP-356)
- document bootstrap.form pattern
1. `npm start`
2. Open http://localhost:3000/components/detail/bootstrap.form.
=> feat(components): bootstrap.form

src/lib/_imports/_bootstrap.css.hbs, src/lib/_imports/_preview.bootstrap.hbs, src/lib/_imports/_preview.hbs, src/lib/_imports/components/_components.config.yml, src/lib/_imports/components/_components.preview.hbs, src/lib/_imports/components/bootstrap/bootstrap.modal/bootstrap.modal.config.yml, src/lib/_imports/components/bootstrap/bootstrap.modal/bootstrap.modal.hbs
DRY-er way to load bootstrap.
- [TUP-356](https://jira.tacc.utexas.edu/browse/TUP-356)
- add bootstrap preview
- replace bootstrap css & js with preview load
- move subdir context to `components` config
- move subdir context to `trumps` config
- use bootstrap preview for bootstrap.modal pattern
See https://github.com/TACC/Core-Styles/pull/51.
=> docs: tup-356 bootstrap preview & easy subdir var

src/lib/_imports/components/bootstrap.container.css, src/lib/_imports/components/bootstrap/bootstrap.container/README.md, src/lib/_imports/components/bootstrap/bootstrap.container/bootstrap.container.config.yml, src/lib/_imports/components/bootstrap/bootstrap.container/bootstrap.container.hbs
Document Bootstrap container.
- [TUP-356](https://jira.tacc.utexas.edu/browse/TUP-356)
- document bootstrap.container pattern
1. `npm start`
2. http://localhost:3000/components/detail/bootstrap.container
| 13" laptop (90% zoom)<br /><sub>1162px preview</sub> | 13" laptop (50% zoom)<br /><sub>1680px preview</sub> | 13" laptop (50% zoom)<br /><sub>1920px preview</sub> |
| - | - | - |
| <img width="1280" alt="tup-356-bootstrap-container" src="https://user-images.githubusercontent.com/62723358/200223072-9529e2e7-8351-456d-8915-3629bbfd256f.png"> | <img width="1280" alt="tup-356-bootstrap-container 1680" src="https://user-images.githubusercontent.com/62723358/200223080-5adb8d22-98e8-41c2-8e9a-665e1a89d6d2.png"> | <img width="1280" alt="tup-356-bootstrap-container 1920" …
=> docs(components): tup-356 bootstrap.container

src/lib/_imports/elements/_elements.config.yml, src/lib/_imports/elements/_elements.preview.hbs, src/lib/_imports/generics/_generics.config.yml, src/lib/_imports/generics/_generics.preview.hbs, src/lib/_imports/objects/_objects.config.yml, src/lib/_imports/objects/_objects.preview.hbs, src/lib/_imports/trumps/_trumps.config.yml, src/lib/_imports/trumps/_trumps.preview.hbs
Simpler way to set `subdir` variable for preview templates.
- continues https://github.com/TACC/Core-Styles/pull/53
- remove preview wrapper templates
- add preview variable (`subdir`) to directory configs
1. `npm start`
2. Open "Trumps".
3. Confirm documented patterns work.
<sup>No other directories have documented patterns yet, and `components` was already tested in #53.</sup>
Skipped.
=> fix(trumps, and unused): complex subdir var made easy

src/lib/_imports/_partials/text-and-link.hbs, src/lib/_imports/elements/links.css, src/lib/_imports/elements/links/docs.css, src/lib/_imports/elements/links/links.hbs, src/lib/_imports/elements/links/readme.md, src/lib/_imports/trumps/s-links-irregular.css, src/lib/_imports/trumps/s-links-irregular/config.yml, src/lib/_imports/trumps/s-links-irregular/readme.md, src/lib/_imports/trumps/s-links-irregular/s-irregular-links.hbs, src/lib/_imports/trumps/s-links-irregular/s-links-irregular.hbs
Add link pattern.
- [TUP-355](https://jira.tacc.utexas.edu/browse/TUP-355)
- add `elements/links`
- add `trumps/irregular-links`
1. `npm run build`
2. `npm start`
3. http://localhost:3000/components/detail/links
4. Review "Elements" > "Links".
4. Review "Trumps" > "Links (Irregular)".
https://user-images.githubusercontent.com/62723358/200469807-9adcc2ed-cac0-44df-8a3e-777ecb329fa5.mov
=> fix: bootstrap form, use template not partials

src/lib/_imports/components/c-button/c-button.config.yml, src/lib/_imports/components/c-button/c-button.hbs
Show `<a>` tag use of `c-button`, unless button is type `c-button--as-link`.
N/A
- add `supports.link-tag` context boolean
- use new context boolean to show `<a>` tag for most `c-button` states
1. `git checkout`
2. `npm run build:css`
3. `npm start`
4. Navigate to [Components > C-Button > Primary](http://localhost:3000/components/detail/c-button--primary).
5. Verify `<a>` examples are shown.
6. Navigate to [Components > C-Button > As Link](http://localhost:3000/components/detail/c-button--as-link).
7. Verify `<a>` examples are **not** shown.
| Primary | As Link |
| - | - |
| ![Primary](https://user-images.githubusercontent.com/62723358/201388337-d7ddd2ff-4c74-48b3-9280-fccc6106b473.png) | ![As Link](https://user-images.githubusercontent.com/62723358/201388332-1894bd01-b8d5-4aec-a6f8-240405 …
=> feat(c-button): do not show <a> tag button for `--as-link`

src/lib/_imports/trumps/s-affixed-input-wrapper.css, src/lib/_imports/trumps/s-affixed-input-wrapper/s-affixed-input-wrapper.hbs
Add `s-affixed-input-wrapper` modifiers `--prefix` and `--suffix`.﹡
<sub>﹡ Because Firefox does not support `:has(…)` by default yet.</sub>
- fixes [FP-1828](https://jira.tacc.utexas.edu/browse/FP-1828)
- required by https://github.com/TACC/Core-CMS-Resources/pull/___
- `s-affixed-input-wrapper--prefix`
- `s-affixed-input-wrapper--suffix`
- use modifiers if browser does not support `:has(*)`
Pattern URL: http://localhost:3000/components/detail/s-affixed-input-wrapper
1. In **Firefox**, open pattern.
2. **Verify** dollar signs are accurately placed.[^1]
3. (optional) Notice dollar sign position is applied via `--prefix` and `--suffix`.
4. In **Edge** or **Chrome**, open pattern.
5. **Verify** dollar signs are accurately placed.[^1]
6. (optional) Notice dollar sign position is applied via …
=> fix: fp-1828 s-affixed-input-wrapper fallback

fractal.config.js, src/lib/_imports/_partials/cms.css.hbs, src/lib/_imports/_preview.hbs, src/lib/_imports/components/bootstrap.css, src/lib/_imports/components/bootstrap/bootstrap--form.hbs, src/lib/_imports/components/bootstrap/bootstrap--modal.hbs, src/lib/_imports/elements/links/links.hbs, src/lib/_imports/elements/table/config.yml, src/lib/_imports/tools/x-link/x-link.hbs, src/lib/_imports/trumps/s-affixed-input-wrapper/s-affixed-input-wrapper.hbs, src/lib/_imports/trumps/s-irregular-links/config.yml, src/lib/_imports/trumps/u-mailto-text-replace/config.yml
Nest demo `.css` files in `/assets` directory.
N/A
- mount web static as `/assets`
- load docs assets from `/assets`
1. Load all pages of pattern library.
2. Verify all stylesheets load.
<sup>You can use Developer Tools "Network" tab.</sup>
Skipped.
=> docs: nest demo assets in `/assets` directory

src/lib/_imports/generics/fonts.css
Hotfix for bad path in #71.
- [FP-1891](https://jira.tacc.utexas.edu/browse/FP-1891)
- fixes #71
Skipped.
=> fix(fonts): fp-1891 wrong path to regular italic

dist/objects/o-fixed-header-table/demo.css, src/lib/_imports/elements/table/table.hbs, src/lib/_imports/objects/o-fixed-header-table/demo.css, src/lib/_imports/objects/o-fixed-header-table/o-fixed-header-table.hbs, src/lib/_imports/objects/o-fixed-header-table/readme.md
Show that `o-fixed-header-table` can be used directly on table (or on wrapper).
N/A
- feat(elements): support table template class param (95021f1)
- feat(elements): add table class param usage (602b8a0)
- fix(o-fixed-header-table): better align examples (09557ec)
- fix(o-fixed-header-table): terse bold wrap notice (634b2ed)
- chore(o-fixed-header-table): don't abuse `<dd>`'s (9a36f9e)
1. Open "O Fixed Table Header".
2. Verify two tables appear.
3. Verify both tables scroll.
4. Verify header on each table stays in view when scrolling.
5. Verify notes clarify that wrapper is not necessary, but just an in-case-you-need it option.
| scroll to top | scroll to bottom |
| - | - |
| ![scroll to top](https://user-images.githubusercontent.com/62723358/206020240-191db22c-b27d-4214-802d-1d58c1a5fe6e.p …
=> feat(o-fixed-header-table): wrapper vs non-wrapper usage

src/lib/_imports/components/cortal.icon.css
Add `collapse` alias, because devs keep thinking it exists, even though it is created as `contract`.
- inspired by https://github.com/TACC/tup-ui/pull/76
Skipped. This change has proven reliable multiple times in the past. I am sorry I do not have time to hunt down instances.
=> feat(cortal.icons): collapse alias

fractal.config.js, src/lib/_imports/_partials/import-client-styles.hbs, src/lib/_imports/_preview.hbs
Load CMS, Portal, and Docs client context styles in CSS `project` layer.
<details><summary>Why do you do this major change right now?</summary>
So Docs client styles take precedence over Base styles like https://github.com/TACC/TACC-Docs styles expects. That client's `core-styles.docs-candidate.css` is being migrated in this PR (which does not work without this infrastructure update):
- #159
</details>
- mimics how theseclients load CSS:
- https://github.com/TACC/TACC-Docs
- [TACC/Core-CMS](https://github.com/TACC/Core-CMS/pull/581)
- https://github.com/TACC/tup-ui
- required by  #159
- **changed** layer in which to load client styles
- **added** logic to use previously ignored layer for client styles
- **added** partial `import-client-styles.hbs` for redundant logic
- **changed** preview …
=> feat: use css "project" layer for client context styles

src/lib/_imports/_partials/figure.hbs, src/lib/_imports/_partials/img.hbs
Add options to support all sample image sizes.
none
- **changed** figure partial to use img partial
- **added** many size options to img partial
1. Load "Components" > "Align".
2. Verify images load.
1. Load "Elements" > "HTML Elements".
2. Verify images load.
| Components | Elements |
| - | - |
| ![components align](https://github.com/TACC/Core-Styles/assets/62723358/a8e95b19-0dbd-4dfc-95d3-e3cf85a1b451) | ![elements html](https://github.com/TACC/Core-Styles/assets/62723358/78427592-6df9-4c3c-8edd-fdf39c554aa8) |
=> feat(_partials): img options to load all sizes

src/lib/_imports/_partials/img-url.hbs, src/lib/_imports/_partials/img.hbs
Add an `img-url` partial (and update `img` partial to use it).
<sup>This lets sample markup authors pick just image URLs (like for `<a>` to use).</sup>
- required by #169
- builds upon #170
1. Load "Components" > "Align".
2. Verify images load.
1. Load "Elements" > "HTML Elements".
2. Verify images load.
| Components | Elements |
| - | - |
| ![components align](https://github.com/TACC/Core-Styles/assets/62723358/a8e95b19-0dbd-4dfc-95d3-e3cf85a1b451) | ![elements html](https://github.com/TACC/Core-Styles/assets/62723358/78427592-6df9-4c3c-8edd-fdf39c554aa8) |
=> feat(partials): add img-url, have img use it

README.md, docs/contributing.md
Isolate and update "How to Contibute" instructions to match [Core-CMS](https://github.com/TACC/Core-CMS) more closely.
- mimics some of https://github.com/TACC/Core-CMS/pull/665
- **moves** contributing documentation to its own doc
View "rich diffs" of the markdown files in the PR diff.
=> docs: isolate & update contrib. docs like core-cms

fractal.config.js, package-lock.json, package.json
Customize Handlebars by adding two helpers, `eq` and `has`.
- required by #195
- **added** handlebars dependency
- **added** handlebars helper `eq` (a **eq**uals b)
- **added** handlebars helper `has` (array **has** item)
```
{{#if (has some_array "some string in that array")}}
Array has the string.
{{/if}}
```
```
{{#if (eq some_string "equal string")}}
Strings are equal.
{{/if}}
```
Tested via #195.
=> feat: handlebars helpers "eq" and "has"

src/lib/_imports/components/c-nav/config.yml
Support nav component that is both "piped" and "boxed".
- adds to #195
- **added** demo of `boxed` + `piped` nav component
1. Verify piped nav component fits in a box with no extra space.
=> fix: demo/support boxed and piped c-nav

src/lib/_imports/elements/form.cms.css
Do not add margin-bottom under checkbox labels.
None.
- moved margin-bottom  for labels to only non-checkbox labels
1. Visit http://localhost:3000/components/detail/c-form--cms.
1. Check that label for a checkbox does **not** have margin-bottom.
| before | after |
| - | - |
| ![before](https://github.com/TACC/Core-Styles/assets/62723358/886f085a-30db-4764-8156-71a0443d6a56) | ![after](https://github.com/TACC/Core-Styles/assets/62723358/443748d7-6072-4c0f-8f3b-c2ea432f1c8f) |
=> fix: checkbox label should not have margin bottom

fractal.config.js, src/lib/_imports/trumps/s-paragraph-table/config.yml
- Load CMS styles in base layer (like TUP does).
- Highlight that `s-paragraph-table` is only for CMS.
- fixes demos that I saw were broken (I feared a bug that would propagate to clients)
1. Open [table--via-paragraphs-cms](http://localhost:3000/components/detail/table--via-paragraphs-cms) and [s-paragraph-table](http://localhost:3000/components/detail/s-paragraph-table).
2. Verify:
- top border is thicker than normal table
- bottom border is present (and thick)
- cells' vertical padding is larger than regular table
- cells (i.e. paragraphs) do **not** have margin
| | Before | After |
| - | - | - |
| table--via-paragraphs-cms | <img width="992" alt="cms before" src="https://github.com/TACC/Core-Styles/assets/62723358/9a943ec2-59de-4607-973b-13fd198a1316"> | <img width="992" alt="cms …
=> fix: cms table & s-paragraph-table demo (demo cmsStyles now in base layer)

.gitignore, package.json, src/lib/_imports/components/admonition/readme.md, src/lib/_utils/js/open-ext-links-in-new-window.js
Reduce duplication of code when component readme has links that should open in new window.
None. This has just been too annoying.
- **added** `.gitignore` rule for demo scripts
- **added** javascript do the job
- **added** auto-run scripts to copy javascript
- **changed** one readme to use new script
1. Open http://localhost:3000/components/detail/admonition.
2. View the "Notes".
3. Click the external link, [“Admonition” messages](https://learning-readthedocs.readthedocs.io/en/latest/Options/admonition.html).
4. Verify link opens in new window.
https://github.com/TACC/Core-Styles/assets/62723358/db5c1fc1-261e-478f-b135-c609989f0672
=> fix: open ext. links in new window code not dry

src/lib/_imports/components/c-button/c-button.hbs
Advertise `c-button--size-small` and `c-button--type-primary` in one button.
<details>This always worked, but was just discouraged. Designer has changed his mind.</details>
- [TUP-599 designer direction (see "1.")](https://jira.tacc.utexas.edu/browse/TUP-599?focusedId=28380&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-28380)
- **changed** `c-button.hbs`
1. Load http://localhost:3002/components/detail/c-button--size-small.
2. Verify small primary buttons appear for `<button>` and `<a>`.
| before | after |
| - | - |
| ![before](https://github.com/TACC/Core-Styles/assets/62723358/c866a617-604a-4867-b117-238822ff8080) | ![after](https://github.com/TACC/Core-Styles/assets/62723358/3110f755-aeb9-43a6-88bf-bfa80037fb56) |
=> docs: allow small primary buttons

fractal.config.js, src/lib/_imports/elements/table/table.hbs
Get correct `data-col` value by using a helper function.
- benefits #275
- **add** new helper function
- **change** `data-col` values to use function
1. Load http://localhost:3000/components/preview/table--cms.
2. Remember column header texts and order.
3. Make screen narrow enough that table design changes.
4. Verify list keys match column headers.
I welcome (beg for) solutions to reduce the verbosity in templates.
=> Task/tup 534  auto get correct data col value

src/lib/_imports/elements/table/config.yml
The nested table was lacking styled pills.
- noticed by designers while reviewing #275
- **added** missing class names
1. Open [/components/detail/table--nested](http://localhost:3000/components/detail/table--nested).
2. Verify nested tables have colored pills.
| before | after |
| - | - |
| <img width="1200" alt="before" src="https://github.com/TACC/Core-Styles/assets/62723358/1b3874ba-d595-436c-900a-c2aee5e930fe"> | <img width="1200" alt="after" src="https://github.com/TACC/Core-Styles/assets/62723358/e8031b83-177f-40d9-b438-97c727aa8dc9"> |
=> fix: missing c-pill styles on nested table

fractal.config.js
Fix CSS specificity bug by not loading docs stylesheet in project layer.
- fixes https://github.com/TACC/Core-Styles/pull/275#discussion_r1466512609
- **changed** layer in which to import docs styles
1. I tested this change on branch at https://github.com/TACC/Core-Styles/pull/275#discussion_r1466512609.
2. I skimmed all the Docs and "… (Docs)" patterns. They didn't look obviously wrong. 
Skipped. I accept all blame.
I want to use layers. I think clients are the correct use case.
But… I keep needing to return client stylesheet imports to base layer to fix demo bugs.
=> fix: load docs in base layer, like other clients

src/lib/_imports/elements/html-elements.cms.css
Fix typo. Set color to match what has been shown.
- near same code as #310
- **fixed** CSS that was inactive
1. Test an `<hr>` on Core-Styles demo that uses CMS stylesheet e.g. http://localhost:3002/components/detail/headings--cms.
2. Verify HR color is set by core-styles and is similar to the color it has been.
1. Replicate changes in a client e.g. on https://tacc.utexas.edu/news/supplemental/2024/02/22/black-history-month-spotlight-cosby/?edit .
2. Verify HR color is set by core-styles and is similar to the color it has been.
| Before | After |
| - | - |
| <img width="1194" alt="broken" src="https://github.com/TACC/Core-Styles/assets/62723358/52be88fa-e845-4c74-9667-e2f10c36069a"> | <img width="1194" alt="working" src="https://github.com/TACC/Core-Styles/assets/62723358/0cf279de-313e-4d6 …
=> hotfix: actually set hr color / fix typo

src/lib/_imports/trumps/s-header.css
- Resolve migration mistake we didn't catch — near duplicate code.
- Fix edge-case-become-common-case* of dropdown CMS nav overflowing header.
<sup>* Edge-case because most CMS's haven't had the newer Core-Styles yet and TACC has used navbar width that avoids the bug. Become-common-case because more CMS's are getting the newer Core-Styles and TACC experienced the bug during development of https://github.com/TACC/tup-ui/pull/416/.</sup>
- [CMD-79](https://tacc-main.atlassian.net/browse/CMD-79)
- **merges** near-duplicate code
- **changes** height to min-height
- **adds** code to avoid logo moving on navbar expand/collapse
https://github.com/TACC/Core-Styles/assets/62723358/a0c3728f-6cbe-4d65-9770-5b5eaddf723c
https://github.com/TACC/Core-Styles/assets/62723358/325a7b72-c6dc-45ab-b264-caffa8 …
=> fix: CMD-79 navbar expanded can overflow header

src/lib/_imports/objects/o-section.css, src/lib/_imports/trumps/s-hero-banner.css
Fix `s-home-banner` page overflow.
- [CMD-105](https://tacc-main.atlassian.net/browse/CMD-105)
- fixes #324
- **added** style to prevent overflow
1. Open https://dev.cep.tacc.utexas.edu/.
2. Make page have vertical scrollbar.
3. Notice page has horizontal scrollbar.
4. Add `max-width: 100%` as in this PR.
3. Notice horizontal scrollbar disappears.
https://github.com/TACC/Core-Styles/assets/62723358/ee4b7b99-72ad-4105-af62-480242713b62
=> fix: CMD-105 overflow on page w/ scrollbar

package-lock.json, package.json, src/.postcssrc.base.yml, src/lib/_imports/components/django-cms-forms.hacks.css
Install (but not use yet) `postcss-mixins`.
- supports #333
- supports #346
- **added** `postcss-mixins` dependency/feature
- **changed** documentation to prefer `@mixin` to `@extend`
Already tested via #333.
N/A
=> feat: WP-280 install postcss-mixins

src/lib/_imports/core-styles.docs.css, src/lib/_imports/trumps/s-document.css, src/lib/_imports/trumps/s-guide-doc.css, src/lib/_imports/trumps/s-inline-dl.css, src/lib/_imports/trumps/u-nested-text-content.css
Deprecate these classes:
- `s-document`
- `s-inline-dl`
- `u-nested-text-content`
<sup>Clients should remove them and use only `.s-guide-doc` wrapper.</sup>
Update this class to take over:
- `s-guide-doc`
<sup>Added styles from deprecated classes but used markup in selectors.</sup>
- [CMD-143](https://tacc-main.atlassian.net/browse/CMD-143)
- required by …
- **commented** "(DEPRECATED)" on some files
- **deleted** comments to consider using some files
- **migrated** deprecated styles (that are not already in `s-guide-doc`)
Skipped.
=> feat: CMD-143 deprecate most CMS document style class names

src/lib/_imports/_preview.hbs
Add `shouldLoadBootstrap5`. Not used yet.
- required by #___
- **added** `shouldLoadBootstrap5` context option
Verify [the CDN URL to the stylesheet](https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css) loads.
Otherwise tested via #__.
Skipped
=> feat: shouldLoadBootstrap5

dist/tools/x-drop-cap.css, dist/tools/x-drop-cap.demo.css, src/lib/_imports/tools/x-drop-cap.css, src/lib/_imports/tools/x-drop-cap.demo.css, src/lib/_imports/tools/x-drop-cap/config.yml, src/lib/_imports/tools/x-drop-cap/readme.md, src/lib/_imports/tools/x-drop-cap/x-drop-cap.hbs, src/lib/_imports/trumps/s-drop-cap.css
Add `drop-cap` as a mixin.
None
- **added** `drop-cap` mixin and demo
- **used** `drop-cap` mixin for `s-drop-cap`
| | [`s-drop-cap`](http://localhost:3000/components/preview/s-drop-cap) | [`x-drop-cap`](http://localhost:3000/components/preview/x-drop-cap) |
| - | - | - |
| chromium | <img alt="chromium s" src="https://github.com/user-attachments/assets/baf1bb3d-d349-40ab-8766-42c3136b905b"> | <img alt="chromium x" src="https://github.com/user-attachments/assets/b01c12ab-5513-4c65-9049-c191beb086ae"> |
| webkit | <img alt="safari s" src="https://github.com/user-attachments/assets/05457e28-f2d1-4cf0-8e57-8352b83e85a3"> | <img alt="safari x" src="https://github.com/user-attachments/assets/a0786dee-07f9-473f-a758-625838e0b3bc"> |
=> feat: drop-cap mixin

package-lock.json, package.json
The `npmr unw atch` command was not rebuilding upon change to CSS file.
I do not know what broke this.
- **updated** `npm-watch`
- **fixed** configuration for `npm-watch`
1. Run `npm run watch`.
2. Change a CSS source file.
3. Verify rebuild is triggered (`dist/` will have changes).
4. Change the `src/lib/tokens.json` file.
5. Verify rebuild is triggered (`dist/` will have changes).
Skipped.
=> fix: npm run watch not working on css

src/lib/_imports/tools/x-overlay.css
Allow using `overlay` as a mixin.
- [WP-280](https://tacc-main.atlassian.net/browse/WP-280)
- expected by https://github.com/TACC/Core-CMS-Custom/pull/293
- **added** `@mixin overlay--…`
- **deprecated** `@extend %x-overlay--…`
Tested via https://github.com/TACC/Core-CMS-Custom/pull/293.
See https://github.com/TACC/Core-CMS-Custom/pull/293.
=> feat: WP-280 @mixin overlay

README.md, bin/build-each.js, package.json, src/bin/build-styles.js, src/main.js
Allow developers to build a file in place.
- **added** `npm run build-each` (`/bin/build-each.js`)
1. Run `npm run build:each -- src/lib/_imports/components/align.postcss src/lib/_imports/components/admonition.postcss`.
2. Verify two files are built and minified:
- `src/lib/_imports/components/align.css`
- `src/lib/_imports/components/admonition.postcss`
0. If present, delete `/dist`.
1. Run `npm run build:css`.
2. Verify no errors.
3. Verify `/dist` is created (with all its regular content).
Skipped.
=> epic/v3: allow dev to build file(s) in place

src/lib/_imports/_preview.hbs
"Bootstrap" patterns are not loading Bootstrap 4, but instead Bootstrap 3.
- fixes #346
- **changed** version of file from CDN
Verify Bootstrap 4 is loaded, not Bootstrap 3, on most Bootstrap patterns.
Skipped.
=> fix(demo): Bootstrap patterns loads v3 instead of v4

src/lib/_imports/components/c-show-more/c-show-more--generated.hbs, src/lib/_imports/components/c-show-more/c-show-more.js
Convert `c-show-more.js` to a JavaScript module (instead of an auto-run script).
- enhances #439
- **updates** `c-show-more.js` to export function and default parameter
- **deletes** auto-run of `c-show-more.js` function
- **creates** script in "C Show More" demo to load and run `c-show-more.js`
1. Visit http://localhost:3000/components/detail/c-show-more--generated.
2. Test "Show Less" / "Show More" links.
https://github.com/user-attachments/assets/11e7c312-14b6-43e0-8dac-c54e86e0bb33
=> enhance: c-show-more.js as module

src/lib/_imports/trumps/s-header.css
Header font should be explicit, so that it is consistent across clients.[^1]
[^1]: Portal does not use the same global font family nor the same global font size medium as CMS.
- to resolve tasks for https://github.com/TACC/Core-Portal/pull/1068
* **changes** font family and size from variable to certain
1. Open http://localhost:3000/components/detail/s-header--with-branding.
2. Verify font size is 14px.
3. Verify font family is `Benton Sans`.
=> fix: header font inconsistent between clients

src/lib/_imports/trumps/s-header.css
Use free fornt instead of paid font, because a free font is easier to replicate across clients.[^1]
[^1]: TACC/Core-Portal has trouble loading Benton Sans font because of relative paths in Core-Styles and Vite asset handling in Core-Portal; TUP's solution failed on Core-Portal (i tested locally and left no paper trail).
- fixes final **obvious** bug from https://github.com/TACC/Core-Portal/pull/1068
- **changed** font for header
1. Open http://localhost:3000/components/detail/s-header--with-branding.
2. Verify font is Roboto.
=> enhance: header use Roboto not Benton

src/lib/_imports/tools/x-pagination.postcss
Pagination should not set font size; it should inherit.
- mimics #475
Setting font size made pagination smaller in Django CMS blog use case.
=> fix: pagination should inherit font size

CHANGELOG.md, bin/release-prepare.sh, docs/contributing.md
Maintaining `CHANGELOG.md` is a chore. I'm not doing that. I can revive it (with missed entries) when it is automated off of GitHub Releases.
- **changed** "unreleased" to "Releases Since 2.40.0"
- **deleted** `CHANGELOG` expectations from release script
- **deleted** `CHANGELOG` expectations from release guide
- #477
=> docs: end changelog maintenance for now

src/lib/_imports/components/c-card/_c-card--image-contact-group.hbs, src/lib/_imports/components/c-card/_c-card--image-link-group.hbs, src/lib/_imports/components/c-card/_c-card--image-position-group.hbs, src/lib/_imports/components/c-card/_c-card--image-variant-section.hbs, src/lib/_imports/components/c-card/c-card--images.hbs
Use partials for demo of cards with images, instead of one giant template.
- makes it easier to do #488
- **added** partials
- **changed** template to use partials
1. Compare http://localhost:3000/components/preview/c-card--images before and after change.
2. They should match.
| before | after |
| - | - |
| ![before](https://github.com/user-attachments/assets/09a2e9d8-6b1e-49a0-bc7a-f4e37bc877dc) | ![after](https://github.com/user-attachments/assets/969aa5ed-b2b4-41fb-b1e7-4941f43ebc1d) |
=> refactor(demo): use partials for cards with images

src/lib/_imports/trumps/s-hero-banner/config.yml, src/lib/_imports/trumps/s-hero-banner/s-hero-banner.hbs
Support `.container` with `.s-overlay`.
- fixes GH-436
- completes [CMD-148](https://tacc-main.atlassian.net/browse/CMD-148)
- **adds** conditional `container` class
1. Open instances to compare:
- http://localhost:3000/components/preview/s-hero-banner--no-container
- http://localhost:3000/components/preview/s-hero-banner--default
2. Resize pages.
3. Notice:
- `--no-container` has white box that, on medium screens, **does** fill page.
- `--default` has white box that, on medium screens, does **not** fill page.
| has container | no container |
| - | - |
| <img width="1024" alt="has-container" src="https://github.com/user-attachments/assets/5505a519-02be-4e1c-a4b9-932d41e9da02" /> | <img width="1024" alt="no-container" src="https://github.com/user-attachments/assets/f7b1f5a5-51e7-4267-a0bd-0 …
=> fix: GH-436 bootstrap container with banner

HOWTO.md, docs/01-index.md, src/lib/_imports/README.md, src/lib/_imports/_preview.hbs, src/lib/_imports/components/c-image-map.css, src/lib/_imports/components/c-pill.css, src/lib/_imports/components/c-pill/readme.md, src/lib/_imports/components/cortal-icon-font.md, src/lib/_imports/components/cortal-icon.css, src/lib/_imports/core-styles.base.css, src/lib/_imports/core-styles.cms.css, src/lib/_imports/core-styles.demo.css, src/lib/_imports/core-styles.docs.css, src/lib/_imports/core-styles.header.css, src/lib/_imports/core-styles.portal.css, src/lib/_imports/core-styles.wysiwyg.css, src/lib/_imports/generics/README.md, src/lib/_imports/generics/fonts.css, src/lib/_imports/settings/font.css, src/lib/_imports/trumps/tacc-search-bar.css
Fix most old Confluence URLs (the ones most likely to be clicked).
=> docs: fix old confluence links (not all, but most)

dist/trumps/s-references.css, src/lib/_imports/trumps/s-references.css, src/lib/_imports/trumps/s-references/config.yml, src/lib/_imports/trumps/s-references/readme.md, src/lib/_imports/trumps/s-references/s-references.hbs
Add `s-references` pattern for a list of publications or other almost-paragraph-but-not-texts
- #418
1. `npm run start`
2. Open http://localhost:3000/components/detail/s-references
=> feat: gh-418 DPM a.k.a. DRP - add `s-references`

src/lib/_utils/js/auto-make-link-text-selectable.js, src/lib/_utils/js/make-link-text-selectable.js
#538 applies `data-text-selectable` to all dynamically-added links by default.
This causes CMS editor interface links to be ineffectual.
- fixes #538
- continues #540
**refactors** parameter names & usage
- **changes** limit future link query to those with attribute
- **fixes** command to unprocess links
0. Be logged in as admin.
1. [Open test page](https://pprd.wtcs.tacc.utexas.edu/wes-demo-for-hedda/?edit).
2. [Update snippet](https://pprd.wtcs.tacc.utexas.edu/admin/djangocms_snippet/snippet/15/change/) to use latest commit from this branch.
3. Verify breadcrumb links navigate browser when clicked.
4. Return to test page.
5. Add `data-text-selectable` on one card link.
6. Verify you can select text on that card link.
7. Double click image to card content to edit.
8. Click "Link" in …
=> fix: make link text selectable kills dynamic links

src/bin/build-styles.js
Log the `postcss` command during build process if process was run with `--verbose`.
=> feat: output command during verbose build
