TACC/Core-Styles

- source/_imports/branding_logos.css
Add new modifier class `.branding-logo--short` for existing class `.branding-logo(--tall)`.
* required by https://github.com/TACC/Core-CMS/pull/476
> feat(branding): new class `.branding-logo--short`

- source/_imports/components/c-page.css
- source/_imports/components/c-page.html
Add new components for pagination: `c-page-list`, `c-page-item`, `c-page-link`, `c-page-end`
* required by https://github.com/TACC/Core-CMS/pull/466
* tested on [TACC/Core-Portal@`task/FP-1596-pagination-core-styles--...` (compare)](https://github.com/TACC/Core-Portal/compare/task/FP-1596-pagination-core-styles--and--task/FP-1491-style-button-component)
> feat(FP-1596): pagination component

- source/_imports/components/c-button.css
- source/_imports/components/c-button.html
Add new button component: `c-button`
* required by https://github.com/TACC/Core-CMS/pull/466
* tested on https://github.com/TACC/Core-Portal/pull/598
> feat(FP-1491): button component

- src/lib/_imports/trumps/s-header.css
- src/lib/_tests.css
Fix miscellaneous inaccuracies in docs and comments since recent updates.
- https://github.com/TACC/Core-CMS/pull/525
- mimics https://github.com/TACC/tup-ui/pull/44
N/A
> chore: update docs & comments

- CHANGELOG.md
- package-lock.json
- package.json
Update to v8.0.0.
N/A
- update changelog
- update package version
N/A
> chore: v8.0.0

- CHANGELOG.md
- package-lock.json
- package.json
Update to `v0.8.6`.
_While on v0.X, I'm bumping patch version for backwards-compatible features and fixes._
N/A
- version update
- changelog update
N/A
> chore: v0.8.6

- src/lib/_imports/_partials/text-and-link.hbs
- src/lib/_imports/elements/links.css
- src/lib/_imports/elements/links/docs.css
- src/lib/_imports/elements/links/links.hbs
- src/lib/_imports/elements/links/readme.md
- src/lib/_imports/trumps/s-links-irregular.css
- src/lib/_imports/trumps/s-links-irregular/config.yml
- src/lib/_imports/trumps/s-links-irregular/readme.md
- src/lib/_imports/trumps/s-links-irregular/s-irregular-links.hbs
Add link pattern.
- [TUP-355](https://jira.tacc.utexas.edu/browse/TUP-355)
- add `elements/links`
- add `trumps/irregular-links`
1. `npm run build`
2. `npm start`
3. http://localhost:3000/components/detail/links
4. Review "Elements" > "Links".
4. Review "Trumps" > "Links (Irregular)".
https://user-images.githubusercontent.com/62723358/200469807-9adcc2ed-cac0-44df-8a3e-777ecb329fa5.mov
> feat: tup-355 links (redo #57)

- CHANGELOG.md
- package-lock.json
- package.json
Release v0.10.0.
N/A
See `CHANGELOG.md`.
N/A
> chore: v0.10.0

- CHANGELOG.md
- package-lock.json
- package.json
Version 0.11.0.
N/A
See `CHANGELOG.md`.
> chore: v0.11.0

- src/lib/_imports/_preview.hbs
Wrap all demo preview content in a `<main>` tag.
I don't know. Something about headings. I am in train–of–auto-pilot–thought—development and this is next.
Skipped because this is a noop on `main` branch.
> feat(demo): wrap all previews in a <main>

- src/lib/_imports/_preview.hbs
Document and update styles (for TUP) of `c-card` and `o-section`.
- required by https://github.com/TACC/tup-ui/pull/97
- available via https://github.com/TACC/Core-CMS/pull/569
- builds atop #87
- builds atop #96
…
1.
…
> feat(components+objects): c-card & o-section

- CHANGELOG.md
- package-lock.json
- package.json
> feat: v2.9.0

- .github/release-drafter.yml
- .github/workflows/label-checker.yaml
- .github/workflows/pr-title-checker.yaml
- .github/workflows/release-drafter.yaml
- .github/workflows/update-changelog.yaml
[Stop writing your changelogs manually.](https://tiagomichaelsousa.dev/articles/stop-writing-your-changelogs-manually)
(all)
- **added** several `.github/` files
Uncertain. GitHub action put says "The configuration file must reside in your default branch."
N/A
> feat: stop writing your changelogs manually

- .github/workflows/pr-label-checker.yaml
Various tests of the GitHub actions for PR labels.
> add comments to pr-label-checker about complex ifs

- README.md
- docs/bootstrap.md
Add Bootstrap doc, and link to it from README.
> docs: add `bootstrap.md`

- docs/bootstrap.md
Document where regular CSS or Core Styles extends, replaces, changes, or yields to Bootstrap.
> docs: core styles relationships to bootstrap

- CHANGELOG.md
- package-lock.json
- package.json
> chore: v2.17.4

- CHANGELOG.md
- package-lock.json
- package.json
> chore: v2.17.5

- src/lib/_imports/_partials/inline-element-samples.hbs
Add partial that #233 had while testing, but was not comitted.
- fixes #233
- **added** `inline-element-samples` partial
See #233.
> fix: c-tag using unavailable partial

- CHANGELOG.md
- package-lock.json
- package.json
> chore: v2.18.0

- src/lib/_imports/objects/o-section.css
- src/lib/_imports/trumps/s-hero-banner.css
> Revert "fix: CMD-105 overflow on page w/ scrollbar"

- src/lib/_imports/components/c-show-more/c-show-more.hbs
- src/lib/_imports/components/c-show-more/config.yml
- src/lib/_imports/components/c-show-more/readme.md
Demo for `c-show-more` component.
None.
- **added** demo
http://localhost:3000/components/detail/c-show-more
https://github.com/user-attachments/assets/32b42bee-607c-4721-a050-faecc9d079df
> docs: c-show-more demo

- src/lib/_imports/components/c-show-more/c-show-more--generated.hbs
- src/lib/_imports/components/c-show-more/c-show-more.hbs
- src/lib/_imports/components/c-show-more/c-show-more.js
- src/lib/_imports/components/c-show-more/config.yml
Offer JavaScript that will convert simple markup into complex markup for CSS show more.
- enhances #438
- **adds** script
0. http://localhost:3000/components/detail/c-show-more--default
Verify feature unchanged.
1. http://localhost:3000/components/detail/c-show-more--generated
Verify feature mimics static version.
https://github.com/user-attachments/assets/9ca85516-d83d-4d32-9163-9dc72e31d46b
https://github.com/user-attachments/assets/61fbd7d0-b108-4441-8918-33c1925807a4
> feat: js-show-more

- src/lib/_imports/components/c-show-more/c-show-more--generated.hbs
- src/lib/_imports/components/c-show-more/c-show-more.hbs
- src/lib/_imports/components/c-show-more/c-show-more.js
Fix several bugs with `c-show-more.js`.
- fixes previous PRs
Not recorded.
1. Not recorded.
Tested on https://pprd.digitalrocks.tacc.utexas.edu/projects/317.
Skipped.
You may see "Datasets" on https://pprd.digitalrocks.tacc.utexas.edu/projects/317.
> fix: c-show-more.js bugs

- src/lib/_imports/trumps/s-header.css
Fix more header UI inconsistencies across clients.
> fix: navbar toggle inconsistent across clients

- CONTRIBUTING.md
- PUBLISHING.md
- README.md
- docs/contributing.config.yml
Split `docs/contributing.md` into `CONTRIBUTING.md` and `PUBLISHING.md`.
- mimics https://github.com/TACC/TACC-Docs
- mimics https://github.com/DesignSafe-CI/DS-User-Guide
Read [`README.md` at "Contributing" and below](https://github.com/TACC/Core-Styles/blob/docs/CONTRIBUTING-and-PUBLISHING/README.md#contributing).
> docs: CONTRIBUTING & PUBLISHING

- .github/workflows/deploy-demo.yml
Deploy the Fractal-powered styles/patterns demo to GitHub Pages.
- **added** a workflow (i.e. GitHub Action config)
1. Merge branch.
2. Verify GitHub Action is run.
3. Verify demo is deployed to https://tacc.github.io/Core-Styles.
https://tacc.github.io/Core-Styles
> feat: deploy demo to GitHub Pages

- src/lib/_imports/components/c-button--cms.css
- src/lib/_imports/components/c-button.css
- src/lib/_imports/components/c-button/c-button.hbs
- src/lib/_imports/components/c-button/config.yml
- Demo: Add icons to buttons.
- Fix: align icons in buttons.
- extracted from #508
1. Review icons in http://localhost:3000/components/detail/c-button--primary.
> fix: add and align icons for buttons

- docs/01-index.md
- src/lib/_imports/_preview.hbs
Bootstrap versions and dependencies were old and/or incomplete and/or inconsistent.
> fix: bootstrap

- dist/trumps/u-image-zoom.css
- dist/trumps/u-image-zoom/u-image-zoom.demo.css
- src/lib/_imports/components/c-card--image-zoom.css
- src/lib/_imports/trumps/u-image-zoom.css
- src/lib/_imports/trumps/u-image-zoom/config.yml
- src/lib/_imports/trumps/u-image-zoom/readme.md
- src/lib/_imports/trumps/u-image-zoom/u-image-zoom.demo.css
- src/lib/_imports/trumps/u-image-zoom/u-image-zoom.hbs
Provide image card images to zoom in on hover.
- https://texascale.org 2025 design request
- **adds** new utility, w/ demo
1. Open http://localhost:3000/components/detail/u-image-zoom.
2. Hvoer over image.
3. Verify image zooms in, but "window" for image is unchanged.
https://github.com/user-attachments/assets/b0b689c3-da79-4581-9dc8-de15ea499d3e
> feat: zoom image on hover
